"""HELD-OUT receipts -- never used while developing the extraction rules.

`ibg_corpus.py` is the training corpus: its 28 samples were in front of the
developers while they wrote the rules, so a 100% score on it is an *in-sample*
score and says nothing about generalization.

This file is the control. Every sample here comes from a receipt the owner
supplied that was NOT transcribed into the corpus and that no rule was ever
tuned against. Scoring against it is the honest measure of whether the label
vocabulary generalizes to unseen documents from the same banks.

Keep it that way: **do not fix a failure by editing this file, and do not move a
sample from here into the corpus.** If a held-out sample fails, either fix the
rule so it generalizes, or record the failure. Moving the goalposts here
destroys the only unbiased measurement available.

Expected values were read off the source PDFs by hand.
"""

from app.ibg.contract import (
    ROLE_BANK_PRIMARY as PRIMARY,
    ROLE_BANK_SECONDARY as SECONDARY,
    ROLE_PAYER_SUPPLIED as PAYER,
)

# --- CIMB ------------------------------------------------------------------

H1_CIMB_DUITNOW_RECEIPT = """RECEIPT
DuitNow
 Transaction Status : Executed Successfully
 Transaction Reference No. : 202608070343889168
 Source Account : 8000000002 / BLUE ORCHID LOGISTICS SDN BHD (MYR)
 Beneficiary Information
 Transfer To : Account No.(DuitNow ID)
 DuitNow ID : 21000000000001 / ACME CONTROL (M) SDN BHD
 Additional Information
 Amount : MYR 392.20
 Transaction Charges : MYR 0.00
 Tax Rate : 0.00 %
 Tax Amount : MYR 0.00
 Total Charges : MYR 0.00
 Total Debit Amount : MYR 392.20
 Recipient Reference : CPC CHARGES
 Other Payment Details : JULY2026
 Remarks : -
 Instruction Mode
 Today : 07-Aug-2026
* This receipt is generated by BizChannel@CIMB
"""

H2_CIMB_IBG_TT_SLIP = """Domestic Transfers
Transfer Information
Transaction Status : Executed Successfully
Reference No. : 202608070343893840
Source Account : 8000000003 / MERIDIAN CARGO FREIGHT(M)SDN BHD (MYR)
Services : Interbank GIRO (IBG)
Beneficiary Bank Information
Bank Name : RHB BANK BHD
Beneficiary Account Information
Account No : 21000000000001
Name : D&D Control (M) Sdn Bhd
Additional Information
Amount : MYR 120.00
Transaction Fee : MYR 0.10
Tax Rate : 0.00%
Tax Amount : MYR 0.00
Total Debit Amount : MYR 120.10
Recipient's Reference : KMT12612040445 -F
Other Payment Details :
Instruction Mode
Today : 07-Aug-2026
cimb.bizchannel.com.my
"""

# --- Public Bank -----------------------------------------------------------

H3_PBB_IBG_APPROVAL = """PBenterprise
Printed Date/Time: 7 Aug 2026 11:34:30
Reference No. : 2608070370955083
Service Reference No. : 015253
Transaction Approval
Transaction Details
Product Type Interbank GIRO (IBG)
Reference No 2608070370955083
Service Reference No 015253
Approval Status Processed
From Account 3800000003 / EASTGATE LOGISTICS SDN. BHD.
Transfer Mode Favourite Account Transfer
Favourite Name ACME CONTROL M SDN BH
Beneficiary Bank RHB Islamic Bank Berhad
Transfer Type Fund Transfer
Beneficiary Name ACME CONTROL M SDN BHD
Beneficiary Account No 21000000000001
Recipient Reference CPC TGCU5520447
Other Payment Details CPC WHSU5877257
Amount MYR 21.20
Fee MYR 0.00
Payment Date 07-Aug-2026
https://secure.pbenterprise.com/PBenterprise/mycms/
"""

H4_PBB_NOTIFICATION_EMAIL = """Notification of Fund Transfer via PB enterprise from Public Bank Berhad
pbenterprise@publicbank.com.my
Dear Sir/Madam,
Please be informed that a fund transfer has been effected via PB enterprise:
SENDER NAME : IRONBARK RESOURCES SDN. BHD.
BENEFICIARY NAME : ACME CONTROL (M) SDN BHD
TRANSACTION DATE & TIME : 07 Aug 2026 11:01:04
TRANSACTION AMOUNT : MYR 10.60
BENEFICIARY BANK : RHB Islamic Bank Berhad
BENEFICIARY ACCOUNT NO. : 2*********0001
REFERENCE NO. : 2608070370921254
RECIPIENT REFERENCE : HAL22610719588
OTHER PAYMENT DETAILS : INNOTECH ETA 31/07
Yours truly,
Public Bank Berhad
"""

# --- Maybank ---------------------------------------------------------------

# Carries RPP Simplified ID and RPP Business Message ID -- two clearing
# references the corpus never exercised together.
H5_MAYBANK_M2E_DUITNOW = """A. Transaction Details
B. Beneficiary Details
Debit From Account No.
557175426311 (MYR) UNITED WORLDWIDE
LOGISTICS SDN. BHD.
Payment Mode
DuitNow (Transfer)
Destination Country
MY - MALAYSIA
Date and Time
31 Jul 2026 14:37:03 MY (UTC+08:00)
Reference No.
MYCN2607316021142
RPP Simplified ID
RPC26073101000027070
RPP Business Message ID
20260731MBBEMYKL010OCB00027070
Customer Ref No.
139120
Debit Reference
BLPV26070190
Debit Description
CLA RELEASE FEE
Transaction Currency
MYR
Transaction Amount
In Transaction Currency
10.60
Value Date (dd-mm-yyyy)
31 Jul 2026 MY (UTC+08:00)
Cash Management System
7/31/26, 4:14 PM Maybank M2E
https://www.maybank2e.com/m2e/portal/tran.view?do=ReLoad# 1/5
"""

H6_MAYBANK2U_BIZ = """Thank You
Here's your receipt.
Transaction Successful
GIRO/DuitNow Transfer 06 Aug 2026, 17:01:53
Reference ID 9490643705
Status Successful
Transfer To ACME CONTROL (M) SDN BHD
Account Number 2100 0000 0000 01
Recipient Bank RHB BANK
Transfer Type Funds Transfer
Transfer Mode DuitNow Transfer
Recipient Reference IM07-0626
Payment Details PGA2 - DETENTION
Amount RM 1,097.10
Malayan Banking Berhad (Co. Reg. : 199001000002)
Maybank2u Biz
"""

H7_MAYBANK2E_ADVICE = """Subject: Payment Advice
From: Maybank2E-admin@maybank.com.my
Date: 6/8/2026, 7:08 pm
Advice
sending
date
 : 06-Aug-2026 MY (UTC+08:00)
Advice
Reference
no
 : MYIG2608067604741
Page : 1/1
Applicant
Details
Contact
Name : WORLDLINK TRADING SDN. BHD.
Beneficiary
Details
Recipient
Name : ACME CONTROL (M) SDN BHD
Beneficiary
Account No. : *******0001
Bank : RHB ISLAMIC BANK
Transaction
Details
Transaction
Type : Outward ACH
Customer
Ref : D&D-EMC9887,0267
Value Date : 06-Aug-2026 MY (UTC+08:00)
Payment
Advice
Amount
 : MYR 160.00
"""

# --- UOB -------------------------------------------------------------------

H8_UOB_DUITNOW = """Successful
Pay to Duitnow Account Number
Bank Reference
FT26080178075640
Application Date: 06/08/2026 RPP Reference Number
20260806UOVBMYKL010OCB02281447
From
Company Name
KESTREL SDN. BHD.
Account Number
1400000001
Currency
MYR
To
Account No.
21000000000001
Payee's Nickname
ACME CONTROL (M) SDN BHD
Bank Name
RHB Bank Berhad
Bank Code
RHBBMYKL
Amount & When
Value Date
06/08/2026
Transaction Amount
1,272.00
Transaction Currency
MYR
Charges
0.00
Recipient Reference
2612039346/2039347
Other Payment Details
PVUOB 2608-069
Date of Export: 06/08/2026 | Time of Export: 16:32:19
"""

# --- OCBC ------------------------------------------------------------------

H9_OCBC_VELOCITY = """DuitNow
Transfer to a bank locally
Transaction Status: Successful
Creation Date: 07 Aug 2026 11:43:26
From To
Your Account
7300000001-MYR APEX FREIGHT (MALAYSIA) SDN. BHD.
Value Date
07 Aug 2026 1,457.50 MYR
Amount
Same day payment
Transfer Type
Fund Transfer
Beneficiary Bank Name
RHB BANK BERHAD
Beneficiary Account No.
21000000000001
Beneficiary Name
ACME CONTROL (M) SDN BHD
Recipient's Reference
GAP12612038153
Other Payment Details
PGPY-69399 I2607343
PayNet Reference No.
20260807OCBCMYKL010OCB27306308
Other Details (optional)
Your Reference No.
PGPY-69399
https://velocity.ocbc.com/digital/web/my/bfo-t2/ift/fund-transfer/duitnow
"""

# --- Hong Leong ------------------------------------------------------------

H10_HONGLEONG_CREDIT_ADVICE = """HongLeong Bank    HongLeong Islamic Bank
connectFirst
CREDIT ADVICE
Dear Sir/Madam,
On request of our customer, we have effected payment to your Account
as per the details below:
Date : 07/08/2026
Ordering Customer Account No. : XXXXXXX0004
Ordering Customer Account Name : BRIGHTPATH SDN BHD
Transaction Details
Transaction Reference No. : C729070826095221
Payment Type : Payment to 3rd Party Account - IBG
Value Date : 07-08-2026
Beneficiary Name : ACME CONTROL (M) SDN BHD
Amount ( MYR ) : 21.20
Beneficiary Account No. : XXXXXXXXXX0001
Beneficiary Bank : RHBB,RHB BANK BHD
Bank Reference No. : IBGCMPRHBB2608070001190
Recipient Reference : INV NO:12041292
Other Details : IA0070726
"""

# --- RHB -------------------------------------------------------------------

# Real non-zero fee: 10.60 + 0.10 = 10.70. The corpus only had zero fees on RHB.
H11_RHB_REFLEX = """Payment - Transaction(s) Authorization
Account Transfer Information
Reference Number
260807488879
Amount
RM 10.60
From Account
21000000000002 / KITA-KAIUN M
To Account
21000000000001 / ACME CONTROL (M) SDN. BHD.
Applicant Resident Status
Resident
Beneficiary Resident Status
Resident
Fund Transfer Charges
RM 0.10
Service Tax Charges
RM 0.00**
Total Amount to Debit
RM 10.70
IC / ID Number
Recipient`s Reference
WHS12612040041
Other Payment Details
CPC
Transfer Type
Immediate Transfer
Payment Date
07-08-2026
"""

# --- AmBank ----------------------------------------------------------------

# Amount is wrapped in asterisks: ***1,696.00***
H12_AMBANK_ADVICE = """AmBank    AmBank Islamic
Payment Details
Payment Ref No. : FIN0608261112374
Payee Account : **********0001
Payee Bank : RHB BANK BERHAD
Recipient Ref/Customer Ref No. : OPS12612035863 WHS12612035912 FL2601181
Other Payment Details : PAONL2608ALF10000049
Payment Value Date Currency Payment Amount Payer Payee
06/08/2026 MYR ***1,696.00*** SERENE LOGISTIK SDN. BHD. ACME CONTROL (M) SDN BHD
"""

# --- Alliance --------------------------------------------------------------

# Beneficiary is OCBC here, not RHB -- the corpus never had that on Alliance.
H13_ALLIANCE_BIZSMART = """Reference No :
Transaction Status :
Transaction Date, Time :
From Account :
Resident Status :
To Account :
Beneficiary Name :
Beneficiary Bank :
Recipient's Reference :
Other Payment Details :
Payment Type :
Payment Date :
Amount (MYR) :
Service Charge(MYR) :
Total Amount(MYR) :
View Successful / Failed - Detail
DuitNow (Pay to Account / Instant Transfer)
AOBIFT03082026933345
Successful
03/08/2026 11:41:26
Payer Details
070000000000001 - ORBIT GLOBAL LOGISTICS SDN. BHD. ( MYR )
Resident
Beneficiary Details
7000000001
ADRIATIC SHIPPING COMPANY
OCBC BANK MALAYSIA BHD
MYPKGPD260008557
MEDUY7519174
Payment Details
Fund Transfer
03/08/2026
180.00
0.00
180.00
https://www.alliancebizsmart.com.my/business/
"""

# --- Standard Chartered ----------------------------------------------------

H14_SCB_PAYEE_ADVICE = """SCB Ref : MY01034Q0056421
Customer Ref : PVSCB2608031
Date : 07/08/2026
Straight2Bank
PAYEE ADVICE
To: COASTAL AGENCIES (M) SDN BHD
/MALAYSIA
Invoice Total 4,375.68
- Benef. Charge 0.00
- Discount 0.00
UTR Reference SB2596260807B346
Dear Sir / Madam (s),
Remittance Advice
This section includes details as supplied by GREENFIELD AGRO-PRODUCE SDN BHD
Payment Details : PYT FOR IPKG2026017633
We have on 07/08/2026 made a payment to your account xxxxxxxx0003 at STANDARD
CHARTERED BANK MALAYSIA BERHAD for MYR 4,375.68 as instructed by TECHNO FRESH
AGRO-PRODUCE SDN BHD.
Page 1
"""

# --- Bank of China ---------------------------------------------------------

# Bilingual Chinese/English, two-column. Nothing like it is in the corpus.
H15_BANKOFCHINA_BILINGUAL = """Request ID: 26217000873
Printed On: 05 Aug 2026 15:38 GMT+8
Financial Transaction Electronic Bank Advice
Txn Ref No. MY02202608050001550497
Financial Txn Type DuitNow iGTB Ref No. 40002124497
Txn Date 2026/08/05 15:31 Txn Status Completed
Payer Beneficiary
Debit Acct Name
PACIFIC INTERNATIONAL LOGISTICS SDN BHD
Name and Addr. D&D *************** BHD
Debit Acct No. 100000000000002
Payer Bank Bank of China Acct No./ IBAN **********0001
Debit Amt MYR 10.00
Payment Details YML12612038690
DuitNow Fee MYR 0.00
Total Fee MYR 0.00
Bene. Bank
Country/Reg Malaysia Bank Name RHB Bank Berhad
Particular DuitNow Outward/YML12612038690
Page 1 of 1
"""


HOLDOUT = [
    {
        "id": "H1_CIMB_DUITNOW_RECEIPT",
        "text": H1_CIMB_DUITNOW_RECEIPT, "ocr_used": False,
        "expected": {
            "reference_id": "202608070343889168",
            "bank_name": "CIMB",
            "transaction_date": "2026-08-07",
            "amount": "392.20", "fee": "0.00", "total_debit": "392.20",
            "references": [("202608070343889168", PRIMARY),
                           ("CPC CHARGES", PAYER), ("JULY2026", PAYER)],
        },
    },
    {
        "id": "H2_CIMB_IBG_TT_SLIP",
        "text": H2_CIMB_IBG_TT_SLIP, "ocr_used": False,
        "expected": {
            "reference_id": "202608070343893840",
            "bank_name": "CIMB",
            "transaction_date": "2026-08-07",
            "amount": "120.00", "fee": "0.10", "total_debit": "120.10",
            "references": [("202608070343893840", PRIMARY),
                           ("KMT12612040445 -F", PAYER)],
        },
    },
    {
        "id": "H3_PBB_IBG_APPROVAL",
        "text": H3_PBB_IBG_APPROVAL, "ocr_used": False,
        "expected": {
            "reference_id": "2608070370955083",
            "bank_name": "Public Bank",
            "transaction_date": "2026-08-07",
            "amount": "21.20", "fee": "0.00", "total_debit": None,
            "references": [("2608070370955083", PRIMARY),
                           ("015253", SECONDARY),
                           ("CPC TGCU5520447", PAYER),
                           ("CPC WHSU5877257", PAYER)],
        },
    },
    {
        "id": "H4_PBB_NOTIFICATION_EMAIL",
        "text": H4_PBB_NOTIFICATION_EMAIL, "ocr_used": False,
        "expected": {
            "reference_id": "2608070370921254",
            "bank_name": "Public Bank",
            "transaction_date": "2026-08-07",
            "amount": "10.60", "fee": None, "total_debit": None,
            "references": [("2608070370921254", PRIMARY),
                           ("HAL22610719588", PAYER),
                           ("INNOTECH ETA 31/07", PAYER)],
        },
    },
    {
        "id": "H5_MAYBANK_M2E_DUITNOW",
        "text": H5_MAYBANK_M2E_DUITNOW, "ocr_used": False,
        "expected": {
            "reference_id": "MYCN2607316021142",
            "bank_name": "Maybank",
            "transaction_date": "2026-07-31",
            "amount": "10.60", "fee": None, "total_debit": None,
            "references": [("MYCN2607316021142", PRIMARY),
                           ("RPC26073101000027070", SECONDARY),
                           ("20260731MBBEMYKL010OCB00027070", SECONDARY),
                           ("139120", PAYER),
                           ("BLPV26070190", PAYER)],
        },
    },
    {
        "id": "H6_MAYBANK2U_BIZ",
        "text": H6_MAYBANK2U_BIZ, "ocr_used": False,
        "expected": {
            "reference_id": "9490643705",
            "bank_name": "Maybank",
            "transaction_date": "2026-08-06",
            "amount": "1097.10", "fee": None, "total_debit": None,
            "references": [("9490643705", PRIMARY), ("IM07-0626", PAYER)],
        },
    },
    {
        "id": "H7_MAYBANK2E_ADVICE",
        "text": H7_MAYBANK2E_ADVICE, "ocr_used": False,
        "expected": {
            "reference_id": "MYIG2608067604741",
            "bank_name": "Maybank",
            "transaction_date": "2026-08-06",
            "amount": "160.00", "fee": None, "total_debit": None,
            "references": [("MYIG2608067604741", PRIMARY),
                           ("D&D-EMC9887,0267", PAYER)],
        },
    },
    {
        "id": "H8_UOB_DUITNOW",
        "text": H8_UOB_DUITNOW, "ocr_used": False,
        "expected": {
            "reference_id": "FT26080178075640",
            "bank_name": "UOB",
            "transaction_date": "2026-08-06",
            "amount": "1272.00", "fee": "0.00", "total_debit": None,
            "references": [("FT26080178075640", PRIMARY),
                           ("20260806UOVBMYKL010OCB02281447", SECONDARY),
                           ("2612039346/2039347", PAYER),
                           ("PVUOB 2608-069", PAYER)],
        },
    },
    {
        "id": "H9_OCBC_VELOCITY",
        "text": H9_OCBC_VELOCITY, "ocr_used": False,
        "expected": {
            "reference_id": "20260807OCBCMYKL010OCB27306308",
            "bank_name": "OCBC",
            "transaction_date": "2026-08-07",
            "amount": "1457.50", "fee": None, "total_debit": None,
            "references": [("20260807OCBCMYKL010OCB27306308", PRIMARY),
                           ("GAP12612038153", PAYER),
                           ("PGPY-69399 I2607343", PAYER),
                           ("PGPY-69399", PAYER)],
        },
    },
    {
        "id": "H10_HONGLEONG_CREDIT_ADVICE",
        "text": H10_HONGLEONG_CREDIT_ADVICE, "ocr_used": False,
        "expected": {
            "reference_id": "C729070826095221",
            "bank_name": "Hong Leong Bank",
            "transaction_date": "2026-08-07",
            "amount": "21.20", "fee": None, "total_debit": None,
            "references": [("C729070826095221", PRIMARY),
                           ("IBGCMPRHBB2608070001190", SECONDARY),
                           ("INV NO:12041292", PAYER),
                           ("IA0070726", PAYER)],
        },
    },
    {
        "id": "H11_RHB_REFLEX",
        "text": H11_RHB_REFLEX, "ocr_used": False,
        "expected": {
            "reference_id": "260807488879",
            "bank_name": "RHB",
            "transaction_date": "2026-08-07",
            "amount": "10.60", "fee": "0.10", "total_debit": "10.70",
            "references": [("260807488879", PRIMARY),
                           ("WHS12612040041", PAYER), ("CPC", PAYER)],
        },
    },
    {
        "id": "H12_AMBANK_ADVICE",
        "text": H12_AMBANK_ADVICE, "ocr_used": False,
        "expected": {
            "reference_id": "FIN0608261112374",
            "bank_name": "AmBank",
            "transaction_date": "2026-08-06",
            "amount": "1696.00", "fee": None, "total_debit": None,
            "references": [("FIN0608261112374", PRIMARY),
                           ("OPS12612035863 WHS12612035912 FL2601181", PAYER),
                           ("PAONL2608ALF10000049", PAYER)],
        },
    },
    {
        "id": "H13_ALLIANCE_BIZSMART",
        "text": H13_ALLIANCE_BIZSMART, "ocr_used": False,
        "expected": {
            "reference_id": "AOBIFT03082026933345",
            "bank_name": "Alliance Bank",
            "beneficiary_bank": "OCBC",
            "transaction_date": "2026-08-03",
            "amount": "180.00", "fee": "0.00", "total_debit": "180.00",
            "references": [("AOBIFT03082026933345", PRIMARY),
                           ("MYPKGPD260008557", PAYER),
                           ("MEDUY7519174", PAYER)],
        },
    },
    {
        "id": "H14_SCB_PAYEE_ADVICE",
        "text": H14_SCB_PAYEE_ADVICE, "ocr_used": False,
        "expected": {
            "reference_id": "MY01034Q0056421",
            "bank_name": "Standard Chartered",
            "transaction_date": "2026-08-07",
            "amount": "4375.68", "fee": "0.00", "total_debit": None,
            "references": [("MY01034Q0056421", PRIMARY),
                           ("SB2596260807B346", SECONDARY),
                           ("PVSCB2608031", PAYER),
                           ("PYT FOR IPKG2026017633", PAYER)],
        },
    },
    {
        "id": "H15_BANKOFCHINA_BILINGUAL",
        "text": H15_BANKOFCHINA_BILINGUAL, "ocr_used": False,
        "expected": {
            "reference_id": "MY02202608050001550497",
            "bank_name": "Bank of China (Malaysia)",
            "transaction_date": "2026-08-05",
            "amount": "10.00", "fee": "0.00", "total_debit": None,
            "references": [("MY02202608050001550497", PRIMARY),
                           ("40002124497", SECONDARY),
                           ("YML12612038690", PAYER)],
        },
    },
]


def cases_for(field):
    for sample in HOLDOUT:
        yield (sample["id"], sample["text"], sample["ocr_used"],
               sample["expected"].get(field), [])


def reference_cases():
    for sample in HOLDOUT:
        yield (sample["id"], sample["text"], sample["ocr_used"],
               sample["expected"].get("references", []))
